Repository DeveloperAcademy-POSTECH/Bingha, pull requests merged in 2022-07, with the labels that each got.

#12 [2022.07.18] feat/carbonEmssionCalculate >> 탄소 배출 저감량 계산 로직 구현
  .gitattributes
  .gitattributes.swp
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Extensions/FormatterExtension.swift
  Bingha/Bingha/Extensions/NumericExtension.swift
  Bingha/Bingha/Views/ReducedCarbonCalculator.swift
Labels: ✨ Feat

#17 [2022.07.19] feat/HealthKit >> HealthKit 데이터 로드 및 이동거리 계산 구현
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Info.plist
  Bingha/Bingha/Views/HealthStore.swift
Labels: ✨ Feat

#18 Feat/result view 결과 화면 제작
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Assets.xcassets/DummyTree.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/DummyTree.imageset/DummyTree.png
  Bingha/Bingha/Views/Home/Complete/Complete.storyboard
  Bingha/Bingha/Views/Home/Complete/CompleteViewController.swift
Labels: ✨ Feat

#20 [2022.07.20] feat/HomeView >> 측정 화면 레이아웃 제작
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Assets.xcassets/StandingMan.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/StandingMan.imageset/standing-up-man-.png
  Bingha/Bingha/Info.plist
  Bingha/Bingha/Views/Home/Complete/Complete.storyboard
  Bingha/Bingha/Views/Home/Measure/Measure.storyboard
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: ✨ Feat

#19 [2022.07.20] feat/binghaUI >> binhaUI 구현
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Assets.xcassets/bingha1.imageset/4254052.jpg
  Bingha/Bingha/Assets.xcassets/bingha1.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/bingha2.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/bingha2.imageset/bingha2.jpg
  Bingha/Bingha/Extensions/UIFontExtension.swift
  Bingha/Bingha/Info.plist
  Bingha/Bingha/Views/Iceberg/CircularProgressBarView.swift
  Bingha/Bingha/Views/Iceberg/Iceberg.storyboard
  Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
  Bingha/Bingha/Views/Iceburg/IceburgNamingTest.swift
Labels: ✨ Feat

#26 [2022.07.20] feat/tabBar >> 탭바 로직 및 UI 구현
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Info.plist
  Bingha/Bingha/Views/Home/Measure/Measure.storyboard
  Bingha/Bingha/Views/Iceberg/Iceberg.storyboard
  Bingha/Bingha/Views/Stat/Stat.storyboard
  Bingha/Bingha/Views/Stat/StatNamingTest.swift
  Bingha/Bingha/Views/Stat/StatViewController.swift
  Bingha/Bingha/Views/TabBar/TabBar.storyboard
Labels: ✨ Feat

#28 [2022.07.20] feat/icebergData >> 빙하 UI에 firestore데이터 불러와서 뷰에 반영
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Views/FirebaseController.swift
  Bingha/Bingha/Views/Iceberg/Iceberg.storyboard
  Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
  Bingha/Bingha/Views/IcebergLevelCalculator.swift
Labels: ✨ Feat

#30 [2022.07.20] feat/result view >> 빙하 레벨업 알림 레이아웃 추가
  Bingha/Bingha/Views/Home/Complete/Complete.storyboard
  Bingha/Bingha/Views/Home/Complete/CompleteViewController.swift
Labels: ✨ Feat

#42 [2022.07.21] feat/HomeViewLottieAnimation >> 측정 화면 로티 애니메이션 백그라운드에서 꺼짐 오류 해결
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: :lady_beetle: Fix

#46 [2022.07.21] feat/ progressFix >> 경험치 바 버그 수정
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/BinghaRelease.entitlements
  Bingha/Bingha/Views/Iceberg/CircularProgressBarView.swift
  Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
  Bingha/Bingha/Views/IcebergLevelCalculator.swift
  Bingha/Pods/Pods.xcodeproj/project.pbxproj
Labels: :lady_beetle: Fix

#44 [2022.07.21] feat/TimerDistanceBugFix >> 타이머 초기화 오류 픽스, 이동거리 데이터 소수점 개수설정 완료
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/BinghaDebug.entitlements
  Bingha/Bingha/Extensions/NumericExtension.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: :lady_beetle: Fix

#48 [Feat] #47 kg 단위에서 g단위로 수정
  Bingha/Bingha/Views/Home/Measure/Measure.storyboard
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: :lady_beetle: Fix

#56 [2022.07.26] feat/coderefactoring >> 코드 리팩토링 및 수정
  Bingha/Bingha/Views/HealthStore.swift
  Bingha/Bingha/Views/Home/Complete/CompleteViewController.swift
  Bingha/Bingha/Views/Home/Measure/Measure.storyboard
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: :hammer: Refactor

#57 [2022.07.26] feat/firebase/refactoring >> 파이어베이스 관련 로직 리팩토링 및 수정
  Bingha/Bingha/Views/FirebaseController.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
  Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
Labels: :hammer: Refactor

#60 [2022.07.26] feat/changeImageAssets >> 이미지 에셋 변경
  Bingha/Bingha/Assets.xcassets/StandingMan.imageset/standing-up-man-.png
  Bingha/Bingha/Assets.xcassets/standing man.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/standing man.imageset/standing man.png
Labels: :art: Design

#62 [2022.07.26] feat/fixImageAssets>> 이미지 에셋 이름 변경 및 위치 수정
  Bingha/Bingha/Assets.xcassets/StandingMan.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/StandingMan.imageset/standing man.png
  Bingha/Bingha/Views/Home/Measure/Measure.storyboard
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: :lady_beetle: Fix

#61 Feat/background animation >> 백그라운드 애니메이션 SwiftUI 파일 추가 및 애니메이션 구현
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Views/Home/Measure/MeasureBackgroundAnimation.swift
  Bingha/Bingha/Views/Iceberg/IcebergBackgroundAnimation.swift
Labels: :art: Design

#63 [2022.07.26] refactor/bingha >> 코드 리팩토링
  Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
  Bingha/Bingha/Views/IcebergLevelCalculator.swift
Labels: :hammer: Refactor

#67 [2022.07.27] feat/ firebase/weekdata >> 주간 데이터 업데이트, 로드 로직 구현
  Bingha/Bingha/Views/FirebaseController.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
  Bingha/Bingha/Views/Iceberg/Iceberg.storyboard
Labels: ✨ Feat

#69 [2022.07.28] feat/firebase/monthdata >> 월간 데이터 업데이트, 로드 로직 구현
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Views/FirebaseController.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: ✨ Feat

#70 [2022.07.28] fix/HealthKitLogic >> HealthKit 권한승인 이후 타이머, 측정시작 동작하도록 로직 수정
  Bingha/Bingha/Views/HealthStore.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: :lady_beetle: Fix

#74 [2022.07.29] feat/connectAnimation >> 홈뷰, 빙하뷰 애니메이션 연결
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
  Bingha/Bingha/Views/Stat/Cells/StatisticsCollectionViewCell.swift
  Bingha/Bingha/Views/Stat/Iceberg/CircularProgressBarView.swift
  Bingha/Bingha/Views/Stat/Iceberg/Iceberg.storyboard
  Bingha/Bingha/Views/Stat/Iceberg/IcebergViewController.swift
Labels: ✨ Feat

#77 [2022.07.29] fix/updateWalkingDistanceLabel >> 측정 시 30초 간격으로 거리측정, 탄소절감 표시되도록 수정
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: :lady_beetle: Fix

#80 [2022.07.30]feat/compareCell >> 통계 탭 레이아웃 완성 2
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Model/CompareModel.swift
  Bingha/Bingha/Views/CompareViewModel.swift
  Bingha/Bingha/Views/Home/Complete/Complete.storyboard
  Bingha/Bingha/Views/Stat/Cells/CompareCollectionViewCell.swift
  Bingha/Bingha/Views/Stat/Cells/CompareCollectionViewCell.xib
  Bingha/Bingha/Views/Stat/Cells/StatisticsCollectionViewCell.swift
  Bingha/Bingha/Views/Stat/Cells/StatisticsCollectionViewCell.xib
  Bingha/Bingha/Views/Stat/Stat.storyboard
  Bingha/Bingha/Views/Stat/StatViewController.swift
Labels: ✨ Feat

#81 [2022.07.30] feat/launchscreen>> 런치스크린 제작
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Info.plist
  Bingha/Bingha/Views/Home/Measure/Measure.storyboard
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
  Bingha/Bingha/Views/Launch/Launch.storyboard
  Bingha/Bingha/Views/Launch/LaunchViewController.swift
Labels: ✨ Feat

#83 [2022.07.31] feat/onboardingEve >> 온보딩 구현
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Assets.xcassets/OnboardingCar.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/OnboardingCar.imageset/car.png
  Bingha/Bingha/Assets.xcassets/OnboardingEarth.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/OnboardingEarth.imageset/earth.png
  Bingha/Bingha/Assets.xcassets/OnboardingHealth.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/OnboardingHealth.imageset/OnboardingHealth.png
  Bingha/Bingha/Assets.xcassets/OnboardingHealth.imageset/OnboardingHealth@2x.png
  Bingha/Bingha/Assets.xcassets/OnboardingHealth.imageset/OnboardingHealth@3x.png
  Bingha/Bingha/Assets.xcassets/OnboardingIceberg.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/OnboardingIceberg.imageset/iceberg.png
  Bingha/Bingha/Assets.xcassets/OnboardingSimulator.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/OnboardingSimulator.imageset/simulator.png
  Bingha/Bingha/Info.plist
  Bingha/Bingha/Onboarding/Onboarding.storyboard
  Bingha/Bingha/Onboarding/OnboardingCollectionViewCell.swift
  Bingha/Bingha/Onboarding/OnboardingDataModel.swift
  Bingha/Bingha/Onboarding/OnboardingViewController.swift
  Bingha/Bingha/Onboarding/RequestAccessView.storyboard
  Bingha/Bingha/Onboarding/RequestAccessViewController.swift
  Bingha/Bingha/SceneDelegate.swift
  Bingha/Bingha/Views/Home/Measure/Measure.storyboard
  Bingha/Bingha/Views/Stat/Iceberg/Iceberg.storyboard
  Bingha/Bingha/Views/Stat/Stat.storyboard
  Bingha/Bingha/Views/Storage.swift
  Bingha/Bingha/Views/TabBar/TabBar.storyboard
Labels: ✨ Feat

#87 [2022.07.31] feat/statview/connectdata >> 통계 화면 데이터 연결, 세그먼트 컨트롤
  Bingha/Bingha/Model/StatisticsModel.swift
  Bingha/Bingha/Views/FirebaseController.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
  Bingha/Bingha/Views/Stat/Cells/StatisticsCollectionViewCell.swift
  Bingha/Bingha/Views/Stat/Stat.storyboard
  Bingha/Bingha/Views/Stat/StatViewController.swift
  Bingha/Bingha/Views/StatisticsViewModel.swift
Labels: ✨ Feat

#89 [2022.07.31] design/AssetFixAndAdd >> 아이콘 및 온보딩 이미지 추가
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/1024.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/120-1.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/120.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/152.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/167.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/180.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/20.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/29.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/40-1.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/40-2.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/40.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/58-1.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/58.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/60.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/76.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/80-1.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/80.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/87.png
  Bingha/Bingha/Assets.xcassets/AppIcon.appiconset/Contents.json
  Bingha/Bingha/Assets.xcassets/ChartTab/Contents.json
  Bingha/Bingha/Assets.xcassets/ChartTab/Earth.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/ChartTab/Earth.imageset/Earth-1.png
  Bingha/Bingha/Assets.xcassets/ChartTab/Earth.imageset/Earth-2.png
  Bingha/Bingha/Assets.xcassets/ChartTab/Earth.imageset/Earth.png
  Bingha/Bingha/Assets.xcassets/ChartTab/Oil.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/ChartTab/Oil.imageset/oil-1.png
  Bingha/Bingha/Assets.xcassets/ChartTab/Oil.imageset/oil-2.png
  Bingha/Bingha/Assets.xcassets/ChartTab/Oil.imageset/oil.png
  Bingha/Bingha/Assets.xcassets/ChartTab/PineTree.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/ChartTab/PineTree.imageset/PineTree-1.png
  Bingha/Bingha/Assets.xcassets/ChartTab/PineTree.imageset/PineTree-2.png
  Bingha/Bingha/Assets.xcassets/ChartTab/PineTree.imageset/PineTree.png
  Bingha/Bingha/Assets.xcassets/OnBoarding/Contents.json
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingFirst.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingFirst.imageset/OnBoarding-1.png
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingFirst.imageset/OnBoarding-2.png
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingFirst.imageset/OnBoarding-3.png
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingFourth.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingFourth.imageset/OnBoarding-4.png
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingFourth.imageset/OnBoarding-5.png
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingFourth.imageset/OnBoarding-6.png
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingSecond.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingSecond.imageset/OnBoarding-2.png
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingSecond.imageset/OnBoarding-3.png
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingSecond.imageset/OnBoarding-4.png
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingThird.imageset/Contents.json
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingThird.imageset/OnBoarding-3.png
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingThird.imageset/OnBoarding-4.png
  Bingha/Bingha/Assets.xcassets/OnBoarding/OnBoardingThird.imageset/OnBoarding-5.png
  Bingha/Bingha/Assets.xcassets/PineTree.imageset/PineTree-1.png
  Bingha/Bingha/Assets.xcassets/PineTree.imageset/PineTree-2.png
  Bingha/Bingha/Assets.xcassets/PineTree.imageset/PineTree.png
Labels: :art: Design

#92 [Feat] #66 온보딩 구현 파일 재업로드
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Onboarding/Onboarding.storyboard
  Bingha/Bingha/Onboarding/OnboardingCollectionViewCell.swift
  Bingha/Bingha/Onboarding/OnboardingDataModel.swift
  Bingha/Bingha/Onboarding/OnboardingViewController.swift
  Bingha/Bingha/Onboarding/RequestAccessView.storyboard
  Bingha/Bingha/Onboarding/RequestAccessViewController.swift
Labels: ✨ Feat

#91 [2022.07.31] fix/collectionViewFix >> 통계 탭 기간당 탄소배출량 섹션 nib으로 뺌
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Model/ReducedCarbonCollectionModel.swift
  Bingha/Bingha/Views/ReducedCarbonCollectionViewModel.swift
  Bingha/Bingha/Views/Stat/Cells/ReducedCarbonCollectionView.swift
  Bingha/Bingha/Views/Stat/Cells/ReducedCarbonCollectionView.xib
  Bingha/Bingha/Views/Stat/Stat.storyboard
  Bingha/Bingha/Views/Stat/StatViewController.swift
Labels: :lady_beetle: Fix

#94 [2022.07.31] feat/iceberg/fixdataflow >> 빙하뷰에서 파이어베이스 로드 로직 삭제, 걷기 종료 시 로컬 데이터 업데이트 로직 추가
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
  Bingha/Bingha/Views/Stat/Iceberg/IcebergViewController.swift
Labels: :lady_beetle: Fix

#98 [2022.07.31] feat/statview/conncet >> 통계 화면 구간 별 탄소 저감량 연결 로직 완성
  Bingha/Bingha/Model/DecreaseCarbonModel.swift
  Bingha/Bingha/Model/ReducedCarbonCollectionModel.swift
  Bingha/Bingha/Views/FirebaseController.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
  Bingha/Bingha/Views/ReducedCarbonCollectionViewModel.swift
  Bingha/Bingha/Views/Stat/Cells/ReducedCarbonCollectionView.swift
  Bingha/Bingha/Views/Stat/StatViewController.swift
Labels: ✨ Feat

#100 [2022.08.01] feat/CoreMotion >> 이동거리측정 로직 CoreMotion으로 구현
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Info.plist
  Bingha/Bingha/Views/HealthStore.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: ✨ Feat

#85 [2022.07.31] feat/license >> 라이센스 페이지 구현
  Bingha/Bingha/Views/Stat/Stat.storyboard
  Bingha/Bingha/Views/Stat/StatViewController.swift
Labels: ✨ Feat

#104 [2022.08.01] feat/bingha >> IcebergBackgroundAnimation 생성자에 빙하 레벨 넣어주기
  Bingha/Bingha/Assets.xcassets/Bingha.imageset/Bingha.png
  Bingha/Bingha/Assets.xcassets/Bingha.imageset/Contents.json
  Bingha/Bingha/Views/Stat/Iceberg/Iceberg.storyboard
  Bingha/Bingha/Views/Stat/Iceberg/IcebergBackgroundAnimation.swift
  Bingha/Bingha/Views/Stat/Iceberg/IcebergViewController.swift
Labels: ✨ Feat

#107 [2022.08.01] feat/Authority >> 온보딩뷰에서 Motion 권한요청, 권한 없을 시 측정뷰에서 권한요청 alert 띄우기 구현
  Bingha/Bingha/Onboarding/RequestAccessViewController.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: ✨ Feat
