Repository DeveloperAcademy-POSTECH/Bingha, pull requests merged in 2022-08, with the labels that each got.

#115 [2022.08.01] feat/calculateCarbonToStat >> 이동거리에 맞게 비유 로직 구현 완료
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/Views/CompareViewModel.swift
  Bingha/Bingha/Views/Home/Complete/Complete.storyboard
  Bingha/Bingha/Views/Home/Complete/CompleteViewController.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
  Bingha/Bingha/Views/Iceberg/CircularProgressBarView.swift
  Bingha/Bingha/Views/Iceberg/Iceberg.storyboard
  Bingha/Bingha/Views/Iceberg/IcebergBackgroundAnimation.swift
  Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
  Bingha/Bingha/Views/ReducedCarbonCalculator.swift
  Bingha/Bingha/Views/Stat/StatViewController.swift
Labels: ✨ Feat

#118 [2022.08.02] feat/chartdesignfix >> 오늘 운동 모으는 부분 시간 텍스트 변경, 라벨 변경,로직 변경
  Bingha/Bingha/Views/FirebaseController.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
  Bingha/Bingha/Views/Stat/Stat.storyboard
Labels: :hammer: Refactor

#119 [2022.08.02] fix/carbonStat >> 통계뷰 로직 수정
  Bingha/Bingha/Views/ReducedCarbonCalculator.swift
  Bingha/Bingha/Views/Stat/StatViewController.swift
Labels: :lady_beetle: Fix

#121 [2022.08.02] build/PortraitIPadSetting
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/AppDelegate.swift
  Bingha/Bingha/Info.plist
Labels: 🤖 Build

#123 [2022.08.02] feat/statviewFix >> 통계 화면 비교 부분 데이터 연결로직 수정, 탭바 한글 수정, 다크모드 수정
  Bingha/Bingha/Model/CompareModel.swift
  Bingha/Bingha/Views/CompareViewModel.swift
  Bingha/Bingha/Views/Home/Measure/Measure.storyboard
  Bingha/Bingha/Views/Iceberg/Iceberg.storyboard
  Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
  Bingha/Bingha/Views/Stat/Stat.storyboard
  Bingha/Bingha/Views/Stat/StatViewController.swift
  Bingha/Bingha/Views/StatisticsViewModel.swift
Labels: :lady_beetle: Fix, :art: Design

#126 [2022.08.02] feat/binghaCharacter >> 레벨에 맞게 빙하 사이즈 조절
  Bingha/Bingha/Views/Iceberg/IcebergBackgroundAnimation.swift
  Bingha/Bingha/Views/Iceberg/IcebergViewController.swift
Labels: ✨ Feat

#128 [2022.08.02] feat/statview/fixdata >> 비교 데이터 수정
  Bingha/Bingha/Views/CompareViewModel.swift
  Bingha/Bingha/Views/Home/Complete/CompleteViewController.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
  Bingha/Bingha/Views/ReducedCarbonCalculator.swift
  Bingha/Bingha/Views/Stat/StatViewController.swift
Labels: :lady_beetle: Fix

#127 [2022.08.02] feat/levelUpNoticeView >> 레벨업 시 완료뷰 안내텍스트 구현
  Bingha/Bingha/Views/Home/Complete/CompleteViewController.swift
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: ✨ Feat

#131 [2022.08.02] docs/licenseView >> 라이센스뷰 탄소절감 관련 자료출처 기입
  Bingha/Bingha/Views/Stat/Stat.storyboard
Labels: :page_facing_up: Docs

#132 [2022.08.02] feat/iceberglocation >> 빙하뷰에서 빙하 위치 변경, 통계뷰 이미지 리매칭
  Bingha/Bingha/Views/CompareViewModel.swift
  Bingha/Bingha/Views/Iceberg/IcebergBackgroundAnimation.swift
Labels: :art: Design

#133 [2022.08.03] fix/timerLabel >> 측정뷰 타이머 60분 넘어가면 60분 안보이던 오류 수정
  Bingha/Bingha/Views/Home/Measure/MeasureViewController.swift
Labels: :lady_beetle: Fix

#135 [2022.08.03] fix/removeHealthKit >> HealthKit 프레임워크 삭제, 관련 권한요청 삭제
  Bingha/Bingha/BinghaDebug.entitlements
  Bingha/Bingha/Views/Home/Complete/Complete.storyboard
Labels: :lady_beetle: Fix

#136 [2022.08.03] fix/binhaSize >> 빙하 크기 변경
  Bingha/Bingha.xcodeproj/project.pbxproj
  Bingha/Bingha/BinghaRelease.entitlements
  Bingha/Bingha/Views/Iceberg/IcebergBackgroundAnimation.swift
Labels: ✨ Feat

#138 [2022.08.03] fix/progressBar >> 프로그래스바 겹쳐보이는 버그 수정
  Bingha/Bingha/Assets.xcassets/ColorSet/ProgressBarBackground.colorset/Contents.json
  Bingha/Bingha/Views/Iceberg/CircularProgressBarView.swift
Labels: :lady_beetle: Fix

#142 [2022.08.03] design/tabview >> 탭뷰 아이콘 변경
  Bingha/Bingha/Views/Home/Measure/Measure.storyboard
Labels: :art: Design
